In [1]:
import numpy as np
import cupy as cp
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm import tqdm
import sigkernel as ksig

# Linear kernel functions breakdown

In [2]:
seq_len = 5
X = np.concatenate([np.arange(seq_len)[np.newaxis,...,np.newaxis], 2*np.arange(seq_len)[np.newaxis,...,np.newaxis]], axis=0)
Y = np.concatenate([np.zeros((1,seq_len,1))-1, np.ones((1,seq_len,1))], axis=0)
print(X.shape, Y.shape, X.reshape((-1, X.shape[-1])).shape, Y.reshape((-1, Y.shape[-1])).shape)
print(X.squeeze())
print(Y.squeeze())
# M_XY = ksig.utils.matrix_mult(X.reshape((-1, X.shape[-1])), Y.reshape((-1, Y.shape[-1])), transpose_Y=True).reshape((X.shape[0], X.shape[1], Y.shape[0], Y.shape[1]))
# print(M_XY)
# M_YX = ksig.utils.matrix_mult(Y.reshape((-1, Y.shape[-1])), X.reshape((-1, X.shape[-1])), transpose_Y=True).reshape((Y.shape[0], Y.shape[1], X.shape[0], X.shape[1]))
# print(M_YX)
M_XX = ksig.utils.matrix_mult(X.reshape((-1, X.shape[-1])), X.reshape((-1, X.shape[-1])), transpose_Y=True).reshape((X.shape[0], X.shape[1], X.shape[0], X.shape[1]))
print(M_XX)
# M_YY = ksig.utils.matrix_mult(Y.reshape((-1, Y.shape[-1])), Y.reshape((-1, Y.shape[-1])), transpose_Y=True).reshape((Y.shape[0], Y.shape[1], Y.shape[0], Y.shape[1]))
# print(M_YY)

(2, 5, 1) (2, 5, 1) (10, 1) (10, 1)
[[0 1 2 3 4]
 [0 2 4 6 8]]
[[-1. -1. -1. -1. -1.]
 [ 1.  1.  1.  1.  1.]]
[[[[ 0  0  0  0  0]
   [ 0  0  0  0  0]]

  [[ 0  1  2  3  4]
   [ 0  2  4  6  8]]

  [[ 0  2  4  6  8]
   [ 0  4  8 12 16]]

  [[ 0  3  6  9 12]
   [ 0  6 12 18 24]]

  [[ 0  4  8 12 16]
   [ 0  8 16 24 32]]]


 [[[ 0  0  0  0  0]
   [ 0  0  0  0  0]]

  [[ 0  2  4  6  8]
   [ 0  4  8 12 16]]

  [[ 0  4  8 12 16]
   [ 0  8 16 24 32]]

  [[ 0  6 12 18 24]
   [ 0 12 24 36 48]]

  [[ 0  8 16 24 32]
   [ 0 16 32 48 64]]]]


In [3]:
kernel = ksig.static.kernels.LinearKernel()
result1 = kernel(X.reshape((-1, X.shape[-1])), Y.reshape((-1, Y.shape[-1]))).reshape((X.shape[0], X.shape[1], Y.shape[0], Y.shape[1]))
result2 = kernel(Y.reshape((-1, Y.shape[-1])), X.reshape((-1, X.shape[-1]))).reshape((Y.shape[0], Y.shape[1], X.shape[0], X.shape[1]))
print(result1.shape)
print(result1)
print(result2)

(2, 5, 2, 5)
[[[[-0. -0. -0. -0. -0.]
   [ 0.  0.  0.  0.  0.]]

  [[-1. -1. -1. -1. -1.]
   [ 1.  1.  1.  1.  1.]]

  [[-2. -2. -2. -2. -2.]
   [ 2.  2.  2.  2.  2.]]

  [[-3. -3. -3. -3. -3.]
   [ 3.  3.  3.  3.  3.]]

  [[-4. -4. -4. -4. -4.]
   [ 4.  4.  4.  4.  4.]]]


 [[[-0. -0. -0. -0. -0.]
   [ 0.  0.  0.  0.  0.]]

  [[-2. -2. -2. -2. -2.]
   [ 2.  2.  2.  2.  2.]]

  [[-4. -4. -4. -4. -4.]
   [ 4.  4.  4.  4.  4.]]

  [[-6. -6. -6. -6. -6.]
   [ 6.  6.  6.  6.  6.]]

  [[-8. -8. -8. -8. -8.]
   [ 8.  8.  8.  8.  8.]]]]
[[[[-0. -1. -2. -3. -4.]
   [-0. -2. -4. -6. -8.]]

  [[-0. -1. -2. -3. -4.]
   [-0. -2. -4. -6. -8.]]

  [[-0. -1. -2. -3. -4.]
   [-0. -2. -4. -6. -8.]]

  [[-0. -1. -2. -3. -4.]
   [-0. -2. -4. -6. -8.]]

  [[-0. -1. -2. -3. -4.]
   [-0. -2. -4. -6. -8.]]]


 [[[ 0.  1.  2.  3.  4.]
   [ 0.  2.  4.  6.  8.]]

  [[ 0.  1.  2.  3.  4.]
   [ 0.  2.  4.  6.  8.]]

  [[ 0.  1.  2.  3.  4.]
   [ 0.  2.  4.  6.  8.]]

  [[ 0.  1.  2.  3.  4.]
   [ 0.  2.  4.  6.  

In [4]:
M_XX

array([[[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  1,  2,  3,  4],
         [ 0,  2,  4,  6,  8]],

        [[ 0,  2,  4,  6,  8],
         [ 0,  4,  8, 12, 16]],

        [[ 0,  3,  6,  9, 12],
         [ 0,  6, 12, 18, 24]],

        [[ 0,  4,  8, 12, 16],
         [ 0,  8, 16, 24, 32]]],


       [[[ 0,  0,  0,  0,  0],
         [ 0,  0,  0,  0,  0]],

        [[ 0,  2,  4,  6,  8],
         [ 0,  4,  8, 12, 16]],

        [[ 0,  4,  8, 12, 16],
         [ 0,  8, 16, 24, 32]],

        [[ 0,  6, 12, 18, 24],
         [ 0, 12, 24, 36, 48]],

        [[ 0,  8, 16, 24, 32],
         [ 0, 16, 32, 48, 64]]]], dtype=int32)

# Diff function

In [5]:
cp.diff(cp.diff(M_XX, axis=1), axis=-1)

array([[[[1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2]],

        [[1, 1, 1, 1],
         [2, 2, 2, 2]]],


       [[[2, 2, 2, 2],
         [4, 4, 4, 4]],

        [[2, 2, 2, 2],
         [4, 4, 4, 4]],

        [[2, 2, 2, 2],
         [4, 4, 4, 4]],

        [[2, 2, 2, 2],
         [4, 4, 4, 4]]]], dtype=int32)

In [6]:
n_levels = 5
static_kernel = ksig.static.kernels.LinearKernel()
sig_kernel = ksig.kernels.SignatureKernel(n_levels, static_kernel=static_kernel, difference=False)

In [7]:
n_samples = 3
sample_len = 10
dt = 1 / 252
X = ksig.tests.gen_GBM_path(mu=0.1, sigma=0.2, dt=dt, n_paths=n_samples, seq_len=sample_len)
Y = ksig.tests.gen_GBM_path(0.1, 0.6, dt, n_samples, sample_len)
X.shape, Y.shape

((3, 10, 1), (3, 10, 1))

In [8]:
sig_kernel(X, Y)

array([[145712.19746647, 178771.40454248, 114262.5250862 ],
       [134518.76291995, 164963.71542871, 105545.99537643],
       [146792.29112953, 180104.16400952, 115103.28435911]])

In [9]:
sig_kernel(Y, X)

array([[145712.19746647, 134518.76291995, 146792.29112953],
       [178771.40454248, 164963.71542871, 180104.16400952],
       [114262.5250862 , 105545.99537643, 115103.28435911]])

In [10]:
sig_kernel(X, X)

array([[132243.63706094, 122112.29528871, 133221.09697798],
       [122112.29528871, 112778.61152517, 123012.68187486],
       [133221.09697798, 123012.68187486, 134206.00472499]])

In [11]:
sig_kernel(X, Y+10)

array([[1.14430566e+10, 1.17036821e+10, 1.11591493e+10],
       [1.04563394e+10, 1.06944362e+10, 1.01969723e+10],
       [1.15389257e+10, 1.18017404e+10, 1.12526337e+10]])

# Signature kernel function

In [12]:
import numpy as np
import cupy as cp

from numbers import Number, Integral
from typing import Optional, Union, List, Tuple

ArrayOnCPU = np.ndarray
ArrayOnGPU = cp.ndarray
ArrayOnCPUOrGPU = Union[cp.ndarray, np.ndarray]

In [13]:
from abc import ABCMeta, abstractmethod
from sklearn.base import BaseEstimator
from ksig import utils

class Kernel(BaseEstimator, metaclass=ABCMeta):
    """Base class for Kernels.

    Warning: This class should not be used directly.
    Use derived classes instead.
    """

    def fit(self, X : ArrayOnCPUOrGPU, y : Optional[ArrayOnCPUOrGPU] = None):
        return self

    @abstractmethod
    def _K(self, X : ArrayOnGPU, Y : Optional[ArrayOnGPU] = None) -> ArrayOnGPU:
        pass

    @abstractmethod
    def _Kdiag(self, X : ArrayOnGPU) -> ArrayOnGPU:
        pass

    def __call__(self, X : ArrayOnCPUOrGPU, Y : Optional[ArrayOnCPUOrGPU] = None, diag : bool = False, return_on_gpu : bool = False) -> ArrayOnCPUOrGPU:
        X = cp.asarray(X)
        Y = cp.asarray(Y) if Y is not None else None
        if diag:
            K = self._Kdiag(X)
        else:
            K =  self._K(X, Y)
        if not return_on_gpu:
            K = cp.asnumpy(K)
        return K

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------

class LinearKernel(Kernel):
    """Class for linear (static) kernel."""

    def __init__(self, sigma : float = 1.0) -> None:
        self.sigma = utils.check_positive_value(sigma, 'sigma')

    def _K(self, X : ArrayOnGPU, Y : Optional[ArrayOnGPU] = None) -> ArrayOnGPU:
        return self.sigma**2 * utils.matrix_mult(X, Y, transpose_Y=True)

    def _Kdiag(self, X : ArrayOnGPU) -> ArrayOnGPU:
        return self.sigma**2 * utils.squared_norm(X, axis=-1)

In [14]:
def multi_cumsum(M : ArrayOnGPU, exclusive : bool = False, axis : int = -1) -> ArrayOnGPU:
    """Computes the exclusive cumulative sum along a given set of axes.

    Args:
        K (cp.ndarray): A matrix over which to compute the cumulative sum
        axis (int or iterable, optional): An axis or a collection of them. Defaults to -1 (the last axis).
    """

    ndim = M.ndim
    axis = [axis] if cp.isscalar(axis) else axis
    axis = [ndim+ax if ax < 0 else ax for ax in axis]

    # create slice for exclusive cumsum (slice off last element along given axis then pre-pad with zeros)
    if exclusive:
        slices = tuple(slice(-1) if ax in axis else slice(None) for ax in range(ndim))
        M = M[slices]

    # compute actual cumsums
    for ax in axis:
        M = cp.cumsum(M, axis=ax)

    # pre-pad with zeros along the given axis if exclusive cumsum
    if exclusive:
        pads = tuple((1, 0) if ax in axis else (0, 0) for ax in range(ndim))
        M = cp.pad(M, pads)

    return M

In [15]:
def signature_kern_higher_order(M : ArrayOnGPU, n_levels : int, order : int, difference : bool = True, return_levels : bool = False) -> ArrayOnGPU:
    """
    Computes the signature kernel matrix with higher-order embedding into the tensor algebra.
    """

    if difference:
        M = cp.diff(cp.diff(M, axis=1), axis=-1)

    if M.ndim == 4:
        n_X, n_Y = M.shape[0], M.shape[2]
        K = cp.ones((n_X, n_Y), dtype=M.dtype)
    else:
        n_X = M.shape[0]
        K = cp.ones((n_X,), dtype=M.dtype)

    if return_levels:
        K = [K, cp.sum(M, axis=(1, -1))]
    else:
        K += cp.sum(M, axis=(1, -1))

    R = cp.copy(M)[None, None, ...]
    for i in range(1, n_levels):
        d = min(i+1, order)
        R_next = cp.empty((d, d) + M.shape, dtype=M.dtype)
        R_next[0, 0] = M * multi_cumsum(cp.sum(R, axis=(0, 1)), exclusive=True, axis=(1, -1))
        for r in range(1, d):
            R_next[0, r] = 1./(r+1) * M * multi_cumsum(cp.sum(R[:, r-1], axis=0), exclusive=True, axis=1)
            R_next[r, 0] = 1./(r+1) * M * multi_cumsum(cp.sum(R[r-1, :], axis=0), exclusive=True, axis=-1)
            for s in range(1, d):
                R_next[r, s] = 1./((r+1)*(s+1)) * M * R[r-1, s-1]
        R = R_next
        if return_levels:
            K.append(cp.sum(R, axis=(0, 1, 3, -1)))
        else:
            K += cp.sum(R, axis=(0, 1, 3, -1))

    return cp.stack(K, axis=0) if return_levels else K

# Order parameter

In [16]:
# simulate geometric Brownian motion paths
X = ksig.tests.gen_GBM_path(mu=0.1, sigma=0.2, dt=0.1, n_paths=3, seq_len=60)
Y = ksig.tests.gen_GBM_path(0.1, 0.3, 0.1, 3, 60)

In [17]:
static_kernel = LinearKernel()

# M = static_kernel(X, diag=True, return_on_gpu=True)

M_X = static_kernel(X.reshape((-1, X.shape[-1])), return_on_gpu=True).reshape((X.shape[0], X.shape[1], X.shape[0], X.shape[1]))
M_Y = static_kernel(Y.reshape((-1, Y.shape[-1])), return_on_gpu=True).reshape((Y.shape[0], Y.shape[1], Y.shape[0], Y.shape[1]))
M_XY = static_kernel(X.reshape((-1, X.shape[-1])), Y.reshape((-1, Y.shape[-1])), return_on_gpu=True).reshape((X.shape[0], X.shape[1], Y.shape[0], Y.shape[1]))
M_YX = static_kernel(Y.reshape((-1, Y.shape[-1])), X.reshape((-1, X.shape[-1])), return_on_gpu=True).reshape((Y.shape[0], Y.shape[1], X.shape[0], X.shape[1]))
M_X.shape, M_Y.shape, M_XY.shape, M_YX.shape

((3, 60, 3, 60), (3, 60, 3, 60), (3, 60, 3, 60), (3, 60, 3, 60))

In [18]:
n_levels = 5
order = 5

sig_orders = []
for i in range(1, n_levels+1):
    sig_XY = signature_kern_higher_order(M_XY, n_levels, i, return_levels=True, difference=True)
    sig_orders.append(sig_XY)

In [19]:
for i in range(n_levels-1):
    pair = np.array([0, 1]) + i
    if not np.allclose(sig_orders[pair[0]], sig_orders[pair[1]]):
        print(f'Order: {pair[0]+1} vs {pair[1]+1}')
        for i in range(n_levels+1):
            print(f'level {i}', np.allclose(sig_orders[pair[0]][i], sig_orders[pair[1]][i]))

Order: 1 vs 2
level 0 True
level 1 True
level 2 False
level 3 False
level 4 False
level 5 False
Order: 2 vs 3
level 0 True
level 1 True
level 2 True
level 3 False
level 4 False
level 5 False
Order: 3 vs 4
level 0 True
level 1 True
level 2 True
level 3 True
level 4 False
level 5 False
Order: 4 vs 5
level 0 True
level 1 True
level 2 True
level 3 True
level 4 True
level 5 False


# Tensor normalisation for characteristic signature kernel

In [20]:
def psi(x, a=1, c=4):
    x = c+c**(1+a)*(c**-a - x**-a)/a if x>4 else x
    return x

In [21]:
def norm_func(lamda, norms, norm_sum, a=1, c=4):
    m = len(norms)
    lamda = np.ones(m) * lamda
    powers = np.arange(m) * 2
    return np.sum(norms * np.power(lamda, powers)) - psi(norm_sum, a, c)

In [22]:
n_levels = 5
order = 5
difference = True
sig_levels_XY = signature_kern_higher_order(M_XY, n_levels, order, return_levels=True, difference=difference)
sig_XY = signature_kern_higher_order(M_XY, n_levels, order, return_levels=False, difference=difference)
sig_levels_YX = signature_kern_higher_order(M_YX, n_levels, order, return_levels=True, difference=difference)
sig_YX = signature_kern_higher_order(M_YX, n_levels, order, return_levels=False, difference=difference)
sig_levels_X = signature_kern_higher_order(M_X, n_levels, order, return_levels=True, difference=difference)
sig_X = signature_kern_higher_order(M_X, n_levels, order, return_levels=False, difference=difference)
sig_levels_Y = signature_kern_higher_order(M_Y, n_levels, order, return_levels=True, difference=difference)
sig_Y = signature_kern_higher_order(M_Y, n_levels, order, return_levels=False, difference=difference)
sig_XY.shape, sig_YX.shape, sig_X.shape, sig_Y.shape, sig_levels_XY.shape, sig_levels_YX.shape, sig_levels_X.shape, sig_levels_Y.shape

((3, 3), (3, 3), (3, 3), (3, 3), (6, 3, 3), (6, 3, 3), (6, 3, 3), (6, 3, 3))

In [35]:
# check that the signature kernel is symmetric
np.allclose(sig_XY, sig_YX.T), np.allclose(sig_X, sig_X.T), np.allclose(sig_Y, sig_Y.T)

(array(True), array(True), array(True))

In [24]:
# gets the squared norm of each level of the signature tensor
ksig.utils.matrix_diag(sig_levels_X) # (normsq of level 0 for all paths, normsq of level 1 for all paths, ...)

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [2.28482214e+00, 2.74430363e-01, 2.42848225e+00],
       [1.30510306e+00, 1.88280060e-02, 1.47438151e+00],
       [3.31325373e-01, 5.74108503e-04, 3.97834369e-01],
       [4.73137218e-02, 9.84705029e-06, 6.03833565e-02],
       [4.32413757e-03, 1.08093183e-07, 5.86559638e-03]])

In [25]:
M = M_X
C = 4.0

M = cp.diff(cp.diff(M, axis=1), axis=-1)

if M.ndim == 4:
    n_X, n_Y = M.shape[0], M.shape[2]
    K = cp.ones((n_X, n_Y), dtype=M.dtype)
else:
    n_X = M.shape[0]
    K = cp.ones((n_X,), dtype=M.dtype)

K = [K, cp.sum(M, axis=(1, -1))]

R = cp.copy(M)[None, None, ...]
for i in range(1, n_levels):
    d = min(i+1, order)
    R_next = cp.empty((d, d) + M.shape, dtype=M.dtype)
    R_next[0, 0] = M * multi_cumsum(cp.sum(R, axis=(0, 1)), exclusive=True, axis=(1, -1))
    for r in range(1, d):
        R_next[0, r] = 1./(r+1) * M * multi_cumsum(cp.sum(R[:, r-1], axis=0), exclusive=True, axis=1)
        R_next[r, 0] = 1./(r+1) * M * multi_cumsum(cp.sum(R[r-1, :], axis=0), exclusive=True, axis=-1)
        for s in range(1, d):
            R_next[r, s] = 1./((r+1)*(s+1)) * M * R[r-1, s-1]
    R = R_next
    K.append(cp.sum(R, axis=(0, 1, 3, -1)))

K = cp.asarray(K)
# get diagonal of signature kernel matrix and transpose to get tensor norm^2 for each path in X
normsq_levels = ksig.utils.matrix_diag(K).T
normsq = np.sum(normsq_levels, axis=1)
norm_condition = normsq > C

In [26]:
normsq, norm_condition

(array([4.97288843, 1.29384243, 5.36694708]), array([ True, False,  True]))

In [27]:
from scipy.optimize import brentq
lamdas = np.ones(n_samples)
for i in range(n_samples):
    if norm_condition[i]:
        lamdas[i] = brentq(norm_func, 0, 1, args=(cp.asnumpy(normsq_levels[i]), cp.asnumpy(normsq[i]).sum(), 1, C))
lamdas

array([0.98405751, 1.        , 0.97360186])

In [41]:
m_lamdas = lamdas[:,np.newaxis] @ lamdas[np.newaxis,:]
m_lamdas = np.power(m_lamdas, np.arange(n_levels+1)[:, np.newaxis, np.newaxis])
m_lamdas, m_lamdas.shape, K.shape

(array([[[1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ],
         [1.        , 1.        , 1.        ]],
 
        [[0.96836918, 0.98405751, 0.95808022],
         [0.98405751, 1.        , 0.97360186],
         [0.95808022, 0.97360186, 0.94790058]],
 
        [[0.93773887, 0.96836918, 0.91791771],
         [0.96836918, 1.        , 0.94790058],
         [0.91791771, 0.94790058, 0.89851551]],
 
        [[0.90807742, 0.95293096, 0.8794388 ],
         [0.95293096, 1.        , 0.92287777],
         [0.8794388 , 0.92287777, 0.85170337]],
 
        [[0.87935419, 0.93773887, 0.84257292],
         [0.93773887, 1.        , 0.89851551],
         [0.84257292, 0.89851551, 0.80733012]],
 
        [[0.8515395 , 0.92278898, 0.80725245],
         [0.92278898, 1.        , 0.87479637],
         [0.80725245, 0.87479637, 0.76526869]]]),
 (6, 3, 3),
 (6, 3, 3))

In [44]:
print(tensor_norms)
print(tensor_norms.sum(axis=1))
print(norm_condition)

[[1.00000000e+00 2.03910166e-03 1.03948389e-06 2.35512591e-10
  3.00146322e-14 2.44811545e-18]
 [1.00000000e+00 3.57861336e-04 3.20161839e-08 1.27303937e-12
  2.84732232e-17 4.07578627e-22]
 [1.00000000e+00 2.06618595e-03 1.06728109e-06 2.45022355e-10
  3.16413591e-14 2.61507726e-18]]
[1.00204014 1.00035789 1.00206725]
[False False False]


In [24]:
test = cp.asarray(np.random.randint(0, 10, size=(5, 3, 3)))
print(test)
ksig.utils.matrix_diag(test).T

[[[0 9 9]
  [8 0 1]
  [7 9 8]]

 [[0 5 4]
  [6 9 8]
  [7 2 7]]

 [[8 6 4]
  [3 6 8]
  [0 9 2]]

 [[0 0 7]
  [5 1 1]
  [6 0 7]]

 [[8 1 8]
  [5 5 5]
  [0 9 5]]]


array([[0, 0, 8, 0, 8],
       [0, 9, 6, 1, 5],
       [8, 7, 2, 7, 5]])

In [ ]:
sum_levels = sig_levels.sum(axis=0)
sum_levels.shape, sig.shape, cp.allclose(sum_levels, sig)

((4, 4), (4, 4), array(True))

In [ ]:
def is_symmetric(X):
    if X.ndim == 2:
        return cp.allclose(X, X.T)
    else:
        raise ValueError('X must be a 2D matrix')

is_symmetric(sig)

array(False)

In [ ]:
sig

array([[0.99468976, 1.00585679, 1.00666171, 1.01360896],
       [0.99984128, 1.00017458, 1.00019853, 1.00040489],
       [1.00472597, 0.99481501, 0.99410465, 0.98799583],
       [1.00436833, 0.99520649, 0.99454969, 0.98890074]])

In [ ]:
norms = signature_kern_higher_order(M_Y, n_levels, order, return_levels=True)
norms.shape

(6, 4, 4)

In [ ]:
for i in range(n_levels + 1):
    print(cp.sqrt(norms[i].diagonal()))


[1. 1. 1. 1.]
[0.07637501 0.084001   0.09552646 0.19481062]
[0.00291657 0.00352808 0.00456265 0.01897559]
[7.42510623e-05 9.87875415e-05 1.45284673e-04 1.23221546e-03]
[1.41773149e-06 2.07456316e-06 3.46963263e-06 6.00121650e-05]
[2.16558528e-08 3.48530776e-08 6.62883444e-08 2.33820144e-06]


In [ ]:
cp.allclose(sig_levels.sum(axis=0), sig)

array(True)

# Permutations of kernel matrix

In [56]:
import numpy as np
from itertools import product
n = 6
m = 4

perm_inds = np.random.permutation(m+n)
X_inds = perm_inds[:n]
Y_inds = perm_inds[n:]

print(perm_inds)
print(X_inds)
print(Y_inds)

[4 1 7 3 9 2 8 5 6 0]
[4 1 7 3 9 2]
[8 5 6 0]


In [53]:
K_XX = np.arange(n*n).reshape((n,n))
K_YY = np.arange(m*m).reshape((m,m)) + n*n
K_XY = np.arange(n*m).reshape((n,m)) + n*n + m*m

print(K_XX)
print(K_YY)
print(K_XY)

In [63]:
def cartesian_product(*arrays):
    la = len(arrays)
    dtype = np.result_type(*arrays)
    arr = np.empty([len(a) for a in arrays] + [la], dtype=dtype)
    for i, a in enumerate(np.ix_(*arrays)):
        arr[...,i] = a
    return arr.reshape(-1, la)

In [65]:
%%time
# len(cartesian_product(X_inds, Y_inds))
perm_X = cartesian_product(X_inds, X_inds)
perm_X

[[4]
 [1]
 [7]
 [3]
 [9]
 [2]]
[[4 1 7 3 9 2]]
CPU times: total: 0 ns
Wall time: 999 µs


array([[4, 4],
       [4, 1],
       [4, 7],
       [4, 3],
       [4, 9],
       [4, 2],
       [1, 4],
       [1, 1],
       [1, 7],
       [1, 3],
       [1, 9],
       [1, 2],
       [7, 4],
       [7, 1],
       [7, 7],
       [7, 3],
       [7, 9],
       [7, 2],
       [3, 4],
       [3, 1],
       [3, 7],
       [3, 3],
       [3, 9],
       [3, 2],
       [9, 4],
       [9, 1],
       [9, 7],
       [9, 3],
       [9, 9],
       [9, 2],
       [2, 4],
       [2, 1],
       [2, 7],
       [2, 3],
       [2, 9],
       [2, 2]])

In [60]:
%%time
# len(np.transpose([np.tile(X_inds, len(Y_inds)), np.repeat(Y_inds, len(X_inds))]))
perm_X = np.transpose([np.tile(X_inds, len(X_inds)), np.repeat(X_inds, len(X_inds))])
type(perm_X)

CPU times: total: 0 ns
Wall time: 0 ns


numpy.ndarray